---
- name: System Provisioning (PHP 8.4 + Nginx + Postgres)
  hosts: localhost
  connection: local
  become: yes
  vars:
    target_user: "{{ target_user | default(lookup('env', 'SUDO_USER') | default(ansible_user_id, true)) }}"
    target_home: "{{ '/root' if target_user == 'root' else '/home/' + target_user }}"
    php_ver: "8.4"
    node_ver: "20"

  
  tasks:
    - name: Install System Packages
      apt:
        update_cache: yes
        name: 
          - sudo
          - acl
          - zip
          - unzip
          - git
          - curl
          - supervisor
          - nginx
          - redis-server
          - postgresql
          - postgresql-client
          - nodejs
        state: present

    - name: Add PHP Repository
      apt_repository: { repo: "ppa:ondrej/php", state: present }

    - name: Install PHP
      apt:
        name:
          - "php{{ php_ver }}"
          - "php{{ php_ver }}-fpm"
          - "php{{ php_ver }}-curl"
          - "php{{ php_ver }}-mbstring"
          - "php{{ php_ver }}-xml"
          - "php{{ php_ver }}-zip"
          - "php{{ php_ver }}-pgsql"
          - "php{{ php_ver }}-bcmath"
          - "php{{ php_ver }}-intl"
          - "php{{ php_ver }}-gd"
          - "php{{ php_ver }}-redis"
          - "php{{ php_ver }}-sqlite3"
        state: latest

    - name: Install Composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      args: { creates: /usr/local/bin/composer }

    - name: Start Services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - "php{{ php_ver }}-fpm"
        - postgresql
        - redis-server
        - supervisor
